### ISSUE TITLE
Cookie issues moving from version 11.0.4 to 11.0.19

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#48]
(Sorry I just posted this under the wrong user name)

Moving from version 11.0.4 to 11.0.19, I am now running into this error in preloading when the preload function makes an api call and no cookies are present:

```
"value" required in setHeader("cookie", value)
    at ClientRequest.setHeader (_http_outgoing.js:365:11)
    at Request.request (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/node_modules/superagent/lib/node/index.js:584:9)
    at Request.end (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/node_modules/superagent/lib/node/index.js:673:18)
    at /Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/build/http client.js:626:20
    at F (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/core-js/library/modules/_export.js:35:28)
    at Http_request.send (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/build/http client.js:625:11)
    at _promise2.default.then.catch_to_retry.getCookie (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/build/http client.js:253:16)
    at F (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/core-js/library/modules/_export.js:35:28)
    at perform_http_request (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/build/http client.js:251:14)
    at http_client._this.(anonymous function) [as get] (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/react-isomorphic-render/build/http client.js:309:13)
```

Any idea what is causing that? I can try to dig in more if you point me in a direction.

**Comment by halt-hammerzeit** [comment]
Hmm, I have a guess, and just released the new version that might fix that (see the commit).

**Comment by adailey14** [comment]
Yes that fixed it, thanks!
